### ISSUE TITLE
./configure stops at ac_cv_lib_FLAC_FLAC__stream_decoder_new=no

### ISSUE THREAD

**Issue by unclebrr** [larsmagne/flac123#1]
Hello,
(I'm a programmer) Trying to compile flac123.0.12 and get the above error. Here is config.log
`This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by flac123 configure 0.0.11, which was
generated by GNU Autoconf 2.59.  Invocation command line was

  $ ./configure 

## --------- ##

hostname = brr-leap
uname -m = x86_64
uname -r = 4.12.14-lp151.28.48-default
uname -s = Linux
uname -v = #1 SMP Fri Apr 17 05:38:36 UTC 2020 (18849d1)

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
hostinfo               = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/brr/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: $PATH
PATH: ~bin/deadbeef-0.7.2
PATH: /usr/bin

## ----------- ##

configure:1172: loading site script /usr/share/site/x86_64-unknown-linux-gnu
| #!/bin/sh
| # Site script for configure. It is resourced via $CONFIG_SITE environment varaible.
| 
| # If user did not specify libdir, guess the correct target:
| # Use lib64 for 64 bit bi-arch targets, keep the default for the rest.
| if test "$libdir" = '${exec_prefix}/lib' ; then
| 
| 	ac_config_site_64bit_host=NONE
| 
| 	case "$host" in
| 	"" )
| 		# User did not specify host target.
| 		# The native platform x86_64 is a bi-arch platform.
| 		# Try to detect cross-compilation to inferior architecture.
| 
| 		# We are trying to guess 32-bit target compilation. It's not as easy as
| 		# it sounds, as there is possible several intermediate combinations.
| 		ac_config_site_cross_to_32bit_host=NONE
| 
| 		# User defined -m32 in CFLAGS or CXXFLAGS or CC or CXX:
| 		# (It's sufficient for 32-bit, but alone may cause mis-behavior of some checks.)
| 		case "$CFLAGS $CXXFLAGS $CC $CXX" in
| 		*-m32*)
| 			ac_config_site_cross_to_32bit_host=YES
| 			;;
| 		esac
| 
| 		# Running with linux32:
| 		# (Changes detected platform, but not the toolchain target.)
| 		case "`/bin/uname -i`" in
| 		x86_64 | ppc64 | s390x | aarch64 )
| 			;;
| 		* )
| 			ac_config_site_cross_to_32bit_host=YES
| 			;;
| 		esac
| 
| 		if test "x$ac_config_site_cross_to_32bit_host" = xNONE; then
| 			ac_config_site_64bit_host=YES
| 		fi
| 
| 		;;
| 	*x86_64* | *ppc64* | *s390x* | *aarch64* )
| 		ac_config_site_64bit_host=YES
| 		;;
| 	esac
| 
| 	if test "x$ac_config_site_64bit_host" = xYES; then
| 		libdir='${exec_prefix}/lib64'
| 	fi
| fi
| 
| # If user did not specify libexecdir, set the correct target:
| # Nor FHS nor openSUSE allow prefix/libexec. Let's default to prefix/lib.
| 
| if test "$libexecdir" = '${exec_prefix}/libexec' ; then
| 	libexecdir='${exec_prefix}/lib'
| fi
| 
| # Continue with the standard behavior of configure defined in AC_SITE_LOAD:
| if test "x$prefix" != xNONE; then
| 	ac_site_file1=$prefix/share/config.site
| 	ac_site_file2=$prefix/etc/config.site
| else
| 	ac_site_file1=$ac_default_prefix/share/config.site
| 	ac_site_file2=$ac_default_prefix/etc/config.site
| fi
| for ac_site_file in "$ac_site_file1" "$ac_site_file2"
| do
| 	test "x$ac_site_file" = xNONE && continue
| 	if test /dev/null != "$ac_site_file" && test -r "$ac_site_file"; then
| 		{ $as_echo "/usr/share/site/x86_64-unknown-linux-gnu:${as_lineno-$LINENO}: loading site script $ac_site_file" >&5
| $as_echo "/usr/share/site/x86_64-unknown-linux-gnu: loading site script $ac_site_file" >&6;}
| 		sed 's/^/| /' "$ac_site_file" >&5
| 		. "$ac_site_file" \
| 			|| { { $as_echo "/usr/share/site/x86_64-unknown-linux-gnu:${as_lineno-$LINENO}: error: in \`$ac_pwd':" >&5
| $as_echo "/usr/share/site/x86_64-unknown-linux-gnu: error: in \`$ac_pwd':" >&2;}
| as_fn_error $? "failed to load site script $ac_site_file
| See \`config.log' for more details" "$LINENO" 5; }
| 	fi
| done
configure:1318: checking for a BSD-compatible install
configure:1373: result: /usr/bin/install -c
configure:1384: checking whether build environment is sane
configure:1427: result: yes
configure:1460: checking for gawk
configure:1476: found /usr/bin/gawk
configure:1486: result: gawk
configure:1496: checking whether make sets $(MAKE)
configure:1516: result: yes
configure:1764: checking for gcc
configure:1780: found /usr/bin/gcc
configure:1790: result: gcc
configure:2034: checking for C compiler version
configure:2037: gcc --version </dev/null >&5
gcc (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2040: $? = 0
configure:2042: gcc -v </dev/null >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none=/usr/nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/7 --enable-ssp --disable-libssp --disable-libvtv --disable-libcc1 --disable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-7 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 7.5.0 (SUSE Linux) 
configure:2045: $? = 0
configure:2047: gcc -V </dev/null >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2050: $? = 1
configure:2073: checking for C compiler default output file name
configure:2076: gcc  -I/usr/local/include   -L/usr/local/lib conftest.c  >&5
configure:2079: $? = 0
configure:2125: result: a.out
configure:2130: checking whether the C compiler works
configure:2136: ./a.out
configure:2139: $? = 0
configure:2156: result: yes
configure:2163: checking whether we are cross compiling
configure:2165: result: no
configure:2168: checking for suffix of executables
configure:2170: gcc -o conftest  -I/usr/local/include   -L/usr/local/lib conftest.c  >&5
configure:2173: $? = 0
configure:2198: result: 
configure:2204: checking for suffix of object files
configure:2225: gcc -c  -I/usr/local/include  conftest.c >&5
configure:2228: $? = 0
configure:2250: result: o
configure:2254: checking whether we are using the GNU C compiler
configure:2278: gcc -c  -I/usr/local/include  conftest.c >&5
configure:2284: $? = 0
configure:2288: test -z 
			 || test ! -s conftest.err
configure:2291: $? = 0
configure:2294: test -s conftest.o
configure:2297: $? = 0
configure:2310: result: yes
configure:2316: checking whether gcc accepts -g
configure:2337: gcc -c -g  conftest.c >&5
configure:2343: $? = 0
configure:2347: test -z 
			 || test ! -s conftest.err
configure:2350: $? = 0
configure:2353: test -s conftest.o
configure:2356: $? = 0
configure:2367: result: yes
configure:2384: checking for gcc option to accept ANSI C
configure:2454: gcc  -c  -I/usr/local/include  conftest.c >&5
configure:2460: $? = 0
configure:2464: test -z 
			 || test ! -s conftest.err
configure:2467: $? = 0
configure:2470: test -s conftest.o
configure:2473: $? = 0
configure:2491: result: none needed
configure:2509: gcc -c  -I/usr/local/include  conftest.c >&5
conftest.c:2:3: error: unknown type name 'choke'
   choke me
   ^~~~~
conftest.c:2:3: error: expected '=', ',', ';', 'asm' or '__attribute__' at end of input
configure:2515: $? = 1
configure: failed program was:
| #ifndef __cplusplus
|   choke me
| #endif
configure:2667: checking for style of include used by make
configure:2695: result: GNU
configure:2723: checking dependency style of gcc
configure:2785: result: gcc3
configure:2793: checking for FLAC__stream_decoder_new in -lFLAC
configure:2823: gcc -o conftest  -I/usr/local/include   -L/usr/local/lib conftest.c -lFLAC -lm  >&5
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lFLAC
collect2: error: ld returned 1 exit status
configure:2829: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| 
| #define PACKAGE_NAME "flac123"
| #define PACKAGE_TARNAME "flac123"
| #define PACKAGE_VERSION "0.0.11"
| #define PACKAGE_STRING "flac123 0.0.11"
| #define PACKAGE_BUGREPORT "kerneljake-at-users-dot-sourceforge-dot-net"
| #define PACKAGE "flac123"
| #define VERSION "0.0.11"
| #define AUDIO_DEFAULT "oss"
| /* end confdefs.h.  */
| 
| /* Override any gcc2 internal prototype to avoid an error.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| /* We use char because int might match the return type of a gcc2
|    builtin and then its argument prototype would still apply.  */
| char FLAC__stream_decoder_new ();
| int
| main ()
| {
| FLAC__stream_decoder_new ();
|   ;
|   return 0;
| }
configure:2855: result: no
configure:2867: error: FLAC required!

## ---------------- ##

ac_cv_c_compiler_gnu=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_exeext=
ac_cv_lib_FLAC_FLAC__stream_decoder_new=no
ac_cv_objext=o
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_stdc=
ac_cv_prog_make_make_set=yes
am_cv_CC_dependencies_compiler_type=gcc3

## ----------------- ##

ACLOCAL='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run aclocal-1.6'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run tar'
AO_CFLAGS=''
AO_LIBS=''
AUTOCONF='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run autoconf'
AUTOHEADER='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run autoheader'
AUTOMAKE='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run automake-1.6'
AWK='gawk'
CC='gcc'
CCDEPMODE='depmode=gcc3'
CFLAGS=' -I/usr/local/include'
CPPFLAGS=''
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EXEEXT=''
FLAC_LIBS=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='${SHELL} $(install_sh) -c -s'
LDFLAGS=' -L/usr/local/lib'
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/brr/flac123-0.0.12-release/flac123-0.0.12/missing --run makeinfo'
OBJEXT='o'
PACKAGE='flac123'
PACKAGE_BUGREPORT='kerneljake-at-users-dot-sourceforge-dot-net'
PACKAGE_NAME='flac123'
PACKAGE_STRING='flac123 0.0.11'
PACKAGE_TARNAME='flac123'
PACKAGE_VERSION='0.0.11'
PATH_SEPARATOR=':'
POPT_LIBS=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION='0.0.11'
ac_ct_CC='gcc'
ac_ct_STRIP=''
am__include='include'
am__quote=''
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${prefix}/share'
exec_prefix='NONE'
host_alias=''
includedir='${prefix}/include'
infodir='${prefix}/info'
install_sh='/home/brr/flac123-0.0.12-release/flac123-0.0.12/install-sh'
libdir='${exec_prefix}/lib64'
libexecdir='${exec_prefix}/lib'
localstatedir='${prefix}/var'
mandir='${prefix}/man'
oldincludedir='/usr/include'
prefix='NONE'
program_transform_name='s,x,x,'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

#define AUDIO_DEFAULT "oss"
#define PACKAGE "flac123"
#define PACKAGE_BUGREPORT "kerneljake-at-users-dot-sourceforge-dot-net"
#define PACKAGE_NAME "flac123"
#define PACKAGE_STRING "flac123 0.0.11"
#define PACKAGE_TARNAME "flac123"
#define PACKAGE_VERSION "0.0.11"
#define VERSION "0.0.11"

configure: exit 1
`
Please help!

**Comment by larsmagne** [comment]
I think that just means that you have to install the libflac-dev package?

**Comment by unclebrr** [comment]
Thank you, yes! Also libao-dev, lilpopt-dev, etc have been in need too :) Anyway it's compiled (1 warning) well.
